FROM node:10.9

# Create app directory
#RUN mkdir /app
WORKDIR /
RUN apt-get update && apt-get install dnsutils -y && apt-get install iputils-ping -y

COPY intake-endpoint/ /

RUN npm install

EXPOSE 8081

RUN ls -l

CMD ["node","index.js"]
